version: '3.9'

networks:
  golang:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - ${PORT}:8080
    networks:
      - golang